"use client";
import { useState } from "react";

type Order = { id: string; customerName: string; phone: string; location: string; notes?: string; total: number; status: string; createdAt: string; items: { id: string; name: string; price: number; quantity: number }[] };
type Reservation = { id: string; name: string; phone: string; date: string; timeSlot: string; partySize: number; status: string };

export default function AdminPage() {
  const [password, setPassword] = useState(""); const [orders, setOrders] = useState<Order[]>([]); const [reservations, setReservations] = useState<Reservation[]>([]); const [message, setMessage] = useState(""); const [loading, setLoading] = useState(false);
  async function loadOrders(e: React.FormEvent) { e.preventDefault(); setLoading(true); const headers = { "x-admin-password": password }; const [orderResponse, reservationResponse] = await Promise.all([fetch("/api/orders", { headers }), fetch("/api/reservations", { headers })]); const orderData = await orderResponse.json(); const reservationData = await reservationResponse.json(); setLoading(false); if (!orderResponse.ok || !reservationResponse.ok) return setMessage(orderData.error || reservationData.error || "Could not load the dashboard."); setOrders(orderData.orders); setReservations(reservationData.reservations); setMessage(`${orderData.orders.length} orders and ${reservationData.reservations.length} table reservations loaded.`); }
  async function updateStatus(id: string, status: string) { const r = await fetch("/api/orders", { method: "PATCH", headers: { "Content-Type": "application/json", "x-admin-password": password }, body: JSON.stringify({ id, status }) }); if (!r.ok) return setMessage("Could not update the order."); setOrders(current => current.map(order => order.id === id ? { ...order, status } : order)); }
  const today = new Date().toDateString(); const todaysOrders = orders.filter(order => new Date(order.createdAt).toDateString() === today); const todaySales = todaysOrders.filter(order => order.status !== "CANCELLED").reduce((sum, order) => sum + order.total, 0);
  return <main className="owner-page"><section className="owner-wrap"><header><p>Bhajiwala owner dashboard</p><h1>Orders for Rajiv.</h1><span>Cash on delivery at Shri Krishna Science Centre</span></header><form className="owner-login" onSubmit={loadOrders}><input value={password} onChange={e => setPassword(e.target.value)} type="password" placeholder="Admin password" required /><button disabled={loading}>{loading ? "Loading..." : "View live orders"}</button></form>{message && <p className="owner-message">{message}</p>}{orders.length > 0 && <div className="owner-stats"><div><span>Today's orders</span><strong>{todaysOrders.length}</strong></div><div><span>Today's sales</span><strong>Rs. {todaySales}</strong></div><div><span>To prepare</span><strong>{orders.filter(order => ["NEW", "ACCEPTED", "COOKING"].includes(order.status)).length}</strong></div></div>}{reservations.length > 0 && <section className="owner-reservations"><div className="owner-section-heading"><div><p>Table reservations</p><h2>Upcoming tables</h2></div><strong>{reservations.length} bookings</strong></div><div className="owner-reservation-grid">{reservations.map(reservation => <article key={reservation.id}><span>{new Date(reservation.date).toLocaleDateString("en-IN", { day: "numeric", month: "short", year: "numeric" })}</span><strong>{reservation.timeSlot}</strong><h3>{reservation.name}</h3><a href={`tel:${reservation.phone}`}>{reservation.phone}</a><p>{reservation.partySize} guest{reservation.partySize === 1 ? "" : "s"}</p><b>{reservation.status}</b></article>)}</div></section>}<div className="owner-orders">{orders.map(order => <article key={order.id}><div className="owner-order-top"><div><b>#{order.id.slice(-6).toUpperCase()}</b><span>{new Date(order.createdAt).toLocaleString()}</span></div><strong>Rs. {order.total}</strong></div><h2>{order.customerName} <a href={`tel:${order.phone}`}>{order.phone}</a></h2><p>{order.location}</p><ul>{order.items.map(item => <li key={item.id}>{item.quantity} x {item.name}<span>Rs. {item.price * item.quantity}</span></li>)}</ul>{order.notes && <small>Note: {order.notes}</small>}<footer><span>Payable to Rajiv Ranjan on delivery</span><b>{order.status.replaceAll("_", " ")}</b></footer><div className="owner-status-actions">{["ACCEPTED", "COOKING", "READY", "OUT_FOR_DELIVERY", "DELIVERED"].map(status => <button key={status} disabled={order.status === status} onClick={() => updateStatus(order.id, status)}>{status.replaceAll("_", " ")}</button>)}</div></article>)}{orders.length === 0 && reservations.length === 0 && message && <p className="owner-empty">No orders or table reservations yet.</p>}</div></section></main>;
}
