"use client";

import { useState } from "react";

type Order = { id: string; customerName: string; phone: string; location: string; notes?: string; total: number; status: string; createdAt: string; items: { id: string; name: string; price: number; quantity: number }[] };
type Reservation = { id: string; name: string; phone: string; date: string; timeSlot: string; partySize: number; status: string };

async function responseData(response: Response) { return response.json().catch(() => ({})); }

export default function AdminPage() {
  const [password, setPassword] = useState(""); const [orders, setOrders] = useState<Order[]>([]); const [reservations, setReservations] = useState<Reservation[]>([]); const [message, setMessage] = useState(""); const [loading, setLoading] = useState(false); const [authenticated, setAuthenticated] = useState(false);
  async function loadDashboard() {
    const [ordersResult, reservationsResult] = await Promise.allSettled([fetch("/api/orders"), fetch("/api/reservations")]);
    const errors: string[] = [];
    if (ordersResult.status === "fulfilled") { const data = await responseData(ordersResult.value); if (ordersResult.value.ok) setOrders(data.orders); else errors.push(data.error || "Could not load orders."); } else errors.push("Could not load orders.");
    if (reservationsResult.status === "fulfilled") { const data = await responseData(reservationsResult.value); if (reservationsResult.value.ok) setReservations(data.reservations); else errors.push(data.error || "Could not load reservations."); } else errors.push("Could not load reservations.");
    setMessage(errors.length ? errors.join(" ") : "Dashboard updated.");
  }
  async function login(e: React.FormEvent) { e.preventDefault(); setLoading(true); try { const response = await fetch("/api/admin/session", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ password }) }); const data = await responseData(response); if (!response.ok) return setMessage(data.error || "Could not sign in."); setAuthenticated(true); setPassword(""); await loadDashboard(); } catch { setMessage("Could not connect to the dashboard."); } finally { setLoading(false); } }
  async function updateStatus(id: string, status: string) { try { const response = await fetch("/api/orders", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id, status }) }); if (!response.ok) { const data = await responseData(response); return setMessage(data.error || "Could not update the order."); } setOrders(current => current.map(order => order.id === id ? { ...order, status } : order)); } catch { setMessage("Could not update the order."); } }
  const today = new Date().toDateString(); const todaysOrders = orders.filter(order => new Date(order.createdAt).toDateString() === today); const todaySales = todaysOrders.filter(order => order.status !== "CANCELLED").reduce((sum, order) => sum + order.total, 0);
  return <main className="owner-page"><section className="owner-wrap"><header><p>Bhajiwala owner dashboard</p><h1>Orders for Rajiv.</h1><span>Cash on delivery at Shri Krishna Science Centre</span></header>{!authenticated ? <form className="owner-login" onSubmit={login}><input value={password} onChange={e => setPassword(e.target.value)} type="password" autoComplete="current-password" placeholder="Admin password" required /><button disabled={loading}>{loading ? "Signing in..." : "View live orders"}</button></form> : <button className="owner-login" onClick={() => { setLoading(true); fetch("/api/admin/session", { method: "DELETE" }).finally(() => { setAuthenticated(false); setOrders([]); setReservations([]); setLoading(false); }); }}>Sign out</button>}{message && <p className="owner-message">{message}</p>}{authenticated && <><div className="owner-stats"><div><span>Today's orders</span><strong>{todaysOrders.length}</strong></div><div><span>Today's sales</span><strong>Rs. {todaySales}</strong></div><div><span>To prepare</span><strong>{orders.filter(order => ["NEW", "ACCEPTED", "COOKING"].includes(order.status)).length}</strong></div></div><section className="owner-reservations"><div className="owner-section-heading"><div><p>Table reservations</p><h2>Upcoming tables</h2></div><strong>{reservations.length} bookings</strong></div><div className="owner-reservation-grid">{reservations.map(reservation => <article key={reservation.id}><span>{new Date(reservation.date).toLocaleDateString("en-IN", { day: "numeric", month: "short", year: "numeric" })}</span><strong>{reservation.timeSlot}</strong><h3>{reservation.name}</h3><a href={`tel:${reservation.phone}`}>{reservation.phone}</a><p>{reservation.partySize} guest{reservation.partySize === 1 ? "" : "s"}</p><b>{reservation.status}</b></article>)}</div></section><div className="owner-orders">{orders.map(order => <article key={order.id}><div className="owner-order-top"><div><b>#{order.id.slice(-6).toUpperCase()}</b><span>{new Date(order.createdAt).toLocaleString()}</span></div><strong>Rs. {order.total}</strong></div><h2>{order.customerName} <a href={`tel:${order.phone}`}>{order.phone}</a></h2><p>{order.location}</p><ul>{order.items.map(item => <li key={item.id}>{item.quantity} x {item.name}<span>Rs. {item.price * item.quantity}</span></li>)}</ul>{order.notes && <small>Note: {order.notes}</small>}<footer><span>Payable to Rajiv Ranjan on delivery</span><b>{order.status.replaceAll("_", " ")}</b></footer><div className="owner-status-actions">{["ACCEPTED", "COOKING", "READY", "OUT_FOR_DELIVERY", "DELIVERED"].map(status => <button key={status} disabled={order.status === status} onClick={() => updateStatus(order.id, status)}>{status.replaceAll("_", " ")}</button>)}</div></article>)}</div></>}</section></main>;
}
